// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udvwklfhrkuvratzcnqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkdndrbGZocmt1dnJhdHpjbnFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MTAwNTgsImV4cCI6MjA2MDk4NjA1OH0.aay2El6OR_BIflOAja1lsLkXlbTexYtKUvLLgQEuuuQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);